(defproject com.kimbsy/minimal "1.0.1-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.12.1"]
                 [org.lwjgl/lwjgl "3.3.6"]
                 [org.lwjgl/lwjgl-assimp "3.3.6"]
                 [org.lwjgl/lwjgl-glfw "3.3.6"]
                 [org.lwjgl/lwjgl-openal "3.3.6"]
                 [org.lwjgl/lwjgl-opengl "3.3.6"]
                 [org.lwjgl/lwjgl-stb "3.3.6"]
                 [org.lwjgl/lwjgl-nanovg "3.3.6"]
                 [org.lwjgl/lwjgl "3.3.6" :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-assimp "3.3.6" :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-glfw "3.3.6" :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-openal "3.3.6" :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-opengl "3.3.6" :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-stb "3.3.6" :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-nanovg "3.3.6" :classifier "natives-linux"]
                 [org.lwjgl/lwjgl "3.3.6" :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-assimp "3.3.6" :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-glfw "3.3.6" :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-openal "3.3.6" :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-opengl "3.3.6" :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-stb "3.3.6" :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-nanovg "3.3.6" :classifier "natives-macos"]
                 [org.lwjgl/lwjgl "3.3.6" :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-assimp "3.3.6" :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-glfw "3.3.6" :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-openal "3.3.6" :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-opengl "3.3.6" :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-stb "3.3.6" :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-nanovg "3.3.6" :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl "3.3.6" :classifier "natives-windows"]
                 [org.lwjgl/lwjgl-assimp "3.3.6" :classifier "natives-windows"]
                 [org.lwjgl/lwjgl-glfw "3.3.6" :classifier "natives-windows"]
                 [org.lwjgl/lwjgl-openal "3.3.6" :classifier "natives-windows"]
                 [org.lwjgl/lwjgl-opengl "3.3.6" :classifier "natives-windows"]
                 [org.lwjgl/lwjgl-stb "3.3.6" :classifier "natives-windows"]
                 [org.lwjgl/lwjgl-nanovg "3.3.6" :classifier "natives-windows"]]
  :main ^:skip-aot minimal.core
  :target-path "target/%s")
