name: Reusable Deploy Workflow

on:
  workflow_call:
    secrets:
      CLOJARS_USERNAME:
        required: true
      CLOJARS_PASSWORD:
        required: true

jobs:
  deploy:
    name: Deploy to Clojars on Java 21
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Leiningen
        run: |
          sudo apt-get update
          sudo apt-get install -y leiningen

      - name: Cache Maven local repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Install dependencies
        run: lein deps

      - name: Deploy to Clojars
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASS: ${{ secrets.CLOJARS_PASSWORD }}
        run: lein deploy clojars
