name: Deploy on main

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'examples/**'
      - 'README.md'

jobs:
  test:
    uses: ./.github/workflows/_test.yml
  
  deploy:
    needs: test
    uses: ./.github/workflows/_deploy.yml
    secrets:
      CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
      CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
