name: Test on every branch

on:
  push:
    branches:
      - "**"
      - '!main' # ignore `main`, that gets tested before deploying
  pull_request:
    branches:
      - "**"

jobs:
  test:
    uses: ./.github/workflows/_test.yml
